# Generated by Django 4.2.23 on 2025-07-08 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_todos', to=settings.AUTH_USER_MODEL),
        ),
    ]
